# Generated by Django 2.1.2 on 2018-10-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='car.CityCar'),
        ),
    ]
