# Generated by Django 2.1.2 on 2018-10-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20181018_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.ManyToManyField(blank=True, default=None, to='car.CityCar'),
        ),
    ]
