# Generated by Django 2.1.2 on 2018-10-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20181018_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
