# Generated by Django 2.1.2 on 2018-10-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20181018_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.ManyToManyField(blank=True, default=None, related_name='city_car', to='car.CityCar'),
        ),
    ]
